nginx:
    build: ./nginx
    links:
        - node1:node1
        - jawbonenode1:jawbonenode1
        - jawboneoauth:jawboneoauth
        #- node2:node2
        #- node3:node3
    ports:
        - "80:80"
        - "443:443"
    extra_hosts: 
        - "www.fotolite.net:127.0.0.1"
node1:
    build: ./node
    links:
        - redis
    ports:
        - "8080"
    extra_hosts: 
        - "www.fotolite.net:127.0.0.1"
jawbonenode1:
    build: ./jawbonenode
    links:
        - redis
    ports:
        - "8081"
    extra_hosts: 
        - "www.fotolite.net:127.0.0.1"

jawboneoauth:
    build: ./jawboneoauth
    links:
        - redis
    ports:
        - "8082"
    extra_hosts: 
        - "www.fotolite.net:127.0.0.1"

redis:
    image: redis
    ports:
        - "6379"
    volumes:
        - /redis_data
    log_driver: "none"